package io.instanto.mockatcha.spi;

import io.instanto.mockatcha.Answer;
import io.instanto.mockatcha.Invocation;
import io.instanto.mockatcha.internal.MockRuntime;
import java.util.ArrayList;
import java.util.List;

/**
 * Lets a library layered on Mockatcha arrange behaviour and read call history by method name.
 *
 * <p>Tests should not need this; use {@code Mockatcha} instead.
 */
public final class MockAccess {

  private MockAccess() {}

  /** Reports whether an object was generated by Mockatcha. */
  public static boolean isMock(Object mock) {
    return MockRuntime.isMock(mock);
  }

  /**
   * Arranges answers for every overload of a method name.
   *
   * <p>Null arguments match every call of that name. Answers are consumed in order, the last
   * repeating.
   */
  public static void arrange(
      Object mock, String methodName, Object[] arguments, List<Answer<?>> answers) {
    MockRuntime.arrangeByName(mock, methodName, arguments, new ArrayList<>(answers));
  }

  /** Removes every stub arranged for a method name, so the mock answers as if never stubbed. */
  public static void clearStubs(Object mock, String methodName) {
    MockRuntime.removeStubsByName(mock, methodName);
  }

  /** Forgets every call recorded on a mock, keeping its arranged behaviour. */
  public static void clearInvocations(Object mock) {
    MockRuntime.clearInvocations(mock);
  }

  /** Forgets the calls recorded for one method name, keeping the rest. */
  public static void clearInvocations(Object mock, String methodName) {
    MockRuntime.clearInvocations(mock, methodName);
  }

  /** Returns every call recorded on a mock, oldest first. */
  public static List<Invocation> invocations(Object mock) {
    return MockRuntime.invocations(mock);
  }

  /** Returns the calls recorded for one method name, oldest first. */
  public static List<Invocation> invocations(Object mock, String methodName) {
    List<Invocation> matching = new ArrayList<>();
    for (Invocation invocation : MockRuntime.invocations(mock)) {
      if (invocation.methodName().equals(methodName)) {
        matching.add(invocation);
      }
    }
    return matching;
  }
}
