package io.instanto.mockatcha.spi;

import io.instanto.mockatcha.Answer;
import io.instanto.mockatcha.Invocation;
import io.instanto.mockatcha.internal.MockRuntime;
import java.util.ArrayList;
import java.util.List;

/**
 * The seam a library layered on Mockatcha uses to reach a mock's runtime state.
 *
 * <p>Tests should not need this. It exists so that an alternative test vocabulary — Oolong is the
 * one in this repository — can arrange behaviour and read call history without depending on
 * Mockatcha's internal packages.
 *
 * <p>Everything here addresses a method by name. The everyday API addresses a method by calling it,
 * which is more precise but cannot describe a call the test is unwilling to evaluate.
 */
public final class MockAccess {

  private MockAccess() {}

  /** Reports whether an object was generated by Mockatcha. */
  public static boolean isMock(Object mock) {
    return MockRuntime.isMock(mock);
  }

  /**
   * Arranges answers for every overload of a method name.
   *
   * <p>Null arguments match every call of that name; an array matches calls whose arguments are
   * equal to it. Answers are consumed in order, and the last one repeats.
   */
  public static void arrange(
      Object mock, String methodName, Object[] arguments, List<Answer<?>> answers) {
    MockRuntime.arrangeByName(mock, methodName, arguments, new ArrayList<>(answers));
  }

  /** Removes every stub arranged for a method name, so the mock answers as if never stubbed. */
  public static void clearStubs(Object mock, String methodName) {
    MockRuntime.removeStubsByName(mock, methodName);
  }

  /** Returns every call recorded on a mock, oldest first. */
  public static List<Invocation> invocations(Object mock) {
    return MockRuntime.invocations(mock);
  }

  /** Returns the calls recorded for one method name, oldest first. */
  public static List<Invocation> invocations(Object mock, String methodName) {
    List<Invocation> matching = new ArrayList<>();
    for (Invocation invocation : MockRuntime.invocations(mock)) {
      if (invocation.methodName().equals(methodName)) {
        matching.add(invocation);
      }
    }
    return matching;
  }
}
